Code/KingsHillMarina/KingsHillMarina.WebApp/Controllers/BoatDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KingsHillMarina.Domain.Abstractions;
using KingsHillMarina.Domain;
using KingsHillMarina.Repositories;
using KingsHillMarina.WebApp.Models;
using KingsHillMarina.Utilities;

namespace KingsHillMarina.WebApp.Controllers
{
    public class BoatDetailsController : BaseController
    {
        private readonly IBoatDetailsService _boatDetailsService;
        private readonly ILookupsService _lookupsService;

        public BoatDetailsController(IBoatDetailsService boatDetailsService, ILookupsService lookupsService)
        {
            this._boatDetailsService = boatDetailsService ?? throw new ArgumentNullException(
                         $"BoatDetailsController expects ctor injection: {nameof(IBoatDetailsService)}");

            this._lookupsService = lookupsService ?? throw new ArgumentNullException(
                        $"BoatDetailsController expects ctor injection: {nameof(ILookupsService)}");
        }


        // GET: Index
        public ActionResult Index()
        {
            var vm = new BoatDetailsVM();

            vm.BoatDetailsList = _boatDetailsService.GetAll()?.ToList();
            vm.BoatMakeList = _lookupsService.GetBoatMakeLookups() as Dictionary<int, string>;
            vm.BoatTypeList = _lookupsService.GetBoatTypeLookups() as Dictionary<int, string>;
            vm.PierList = _lookupsService.GetPiers()?.ToList();

            return View(vm);
        }


        [HttpPost]
        public ActionResult Save(BoatDetailsVM model)
        {
            var vm = new BoatDetailsVM();
            string resultMsg = "Boat Details saved successfully";

            var boatDetails = model.BoatDetails;
            
            //Validate 
            if (string.IsNullOrWhiteSpace(boatDetails.Name))
            {
                return Json(
                    new
                    {
                        success = false,
                        msg = "Please supply boat name and continue.... "
                    });
            }

            if (boatDetails.Length <= 0)
            {
                return Json(
                    new
                    {
                        success = false,
                        msg = "Please supply boat length and continue.... "
                    });
            }


            if (boatDetails.MakeId == 0)
            {
                return Json(
                    new
                    {
                        success = false,
                        msg = "Please supply boat make and continue.... "
                    });
            }



            if (boatDetails.TypeId == 0)
            {
                return Json(
                    new
                    {
                        success = false,
                        msg = "Please supply boat type and continue.... "
                    });
            }


            if (string.IsNullOrWhiteSpace(boatDetails.Pier))
            {
                return Json(
                    new
                    {
                        success = false,
                        msg = "Please supply the pier and continue.... "
                    });
            }

            if (string.IsNullOrWhiteSpace(boatDetails.Berth))
            {
                return Json(
                    new
                    {
                        success = false,
                        msg = "Please supply the berth and continue.... "
                    });
            }

            if (string.IsNullOrWhiteSpace(boatDetails.OwnerFirstName))
            {
                return Json(
                    new
                    {
                        success = false,
                        msg = "Please supply the owner's first name and continue.... "
                    });
            }

            if (string.IsNullOrWhiteSpace(boatDetails.OwnerLastName))
            {
                return Json(
                    new
                    {
                        success = false,
                        msg = "Please supply the owner's last name and continue.... "
                    });
            }

            if (string.IsNullOrWhiteSpace(boatDetails.OwnerTelephone))
            {
                return Json(
                    new
                    {
                        success = false,
                        msg = "Please supply the owner's telehopne number and continue.... "
                    });
            }

            if (string.IsNullOrWhiteSpace(boatDetails.OwnerEmail))
            {
                return Json(
                    new
                    {
                        success = false,
                        msg = "Please supply the owner's email address and continue.... "
                    });
            }

            bool result = _boatDetailsService.Save(boatDetails);

            if (!result)
            {
                resultMsg = "Boat Details saving failed!";
            }
 
            vm.BoatDetailsList = _boatDetailsService.GetAll()?.ToList();

            var partialView = RenderPartialViewToString(
                                   "_BoatDetailsGrid",
                                   vm);

            JsonResult jsonResult = Json(new
            {
                success = result,
                msg = resultMsg,
                partialView = partialView
            }, JsonRequestBehavior.AllowGet);

            //The default is 102400 characters: http://msdn.microsoft.com/en-us/library/system.web.configuration.scriptingjsonserializationsection.maxjsonlength(v=vs.110).aspx
            jsonResult.MaxJsonLength = int.MaxValue;  //The value of this constant is 2,147,483,647

            return jsonResult;
        }

        public ActionResult GetById(int id)
        {
            var boatDetail = _boatDetailsService.GetById(id);
            return Json(boatDetail, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Deactivate(int id)
        {
            string resultMsg = "Boat Details deactivated successfully";
            var vm = new BoatDetailsVM();
            var result = _boatDetailsService.Deactivate(id);

            if (!result)
            {
                resultMsg = "Boat Details deactivation failed!";
            }
         
            vm.BoatDetailsList = _boatDetailsService.GetAll()?.ToList();

            var partialView = RenderPartialViewToString(
                                  "_BoatDetailsGrid",
                                  vm);

            JsonResult jsonResult = Json(new
            {
                success = result,
                msg = resultMsg,
                partial = partialView
            }, JsonRequestBehavior.AllowGet);

            //The default is 102400 characters: http://msdn.microsoft.com/en-us/library/system.web.configuration.scriptingjsonserializationsection.maxjsonlength(v=vs.110).aspx
            jsonResult.MaxJsonLength = int.MaxValue;  //The value of this constant is 2,147,483,647

            return jsonResult;

        }


    }
}

Code/KingsHillMarina/KingsHillMarina.WebApp/Views/BoatDetails/Index.cshtml
@model KingsHillMarina.WebApp.Models.BoatDetailsVM

@{
    ViewBag.Title = "Boat Details";
}

<div class="col-sm-12 bs-callout bs-callout-danger">

    <p class="well lead bs-callout bs-callout-danger" style="font-weight:bolder">Boat Details</p>

    <div class="row">
        <div class="col-xs-12">
            @{
                Html.RenderPartial("_BoatDetailsForm", Model);
            }

        </div>
    </div>

    <hr />

    <div class="row">
        <div class="col-xs-12" id="divContent">
            @{
                Html.RenderPartial("_BoatDetailsGrid", Model);
            }

        </div>
    </div>

</div>



<script type="text/javascript" src="~/Scripts/Custom/BoatDetails.js?v=@DateTime.Now.ToString("yyyyMMddHHmmss")"></script>

Code/KingsHillMarina/KingsHillMarina.WebApp/Views/BoatDetails/_BoatDetailsForm.cshtml
@model KingsHillMarina.WebApp.Models.BoatDetailsVM


@using (Html.BeginForm("Save", "BoatDetails", FormMethod.Post, new { @class = "form-horizontal form-group-sm", @style = "margin-top: 20px;", @id = "form_boatdetails" }))
{

    @Html.HiddenFor(m => m.BoatDetails.Id);

<div class="row">
    <div class="col-sm-1 text-left">
        <label class="control-label">Name:</label>
    </div>

    <div class="col-sm-2 form-group">
        @Html.TextBoxFor(m => m.BoatDetails.Name, new { @class = "form-control", @style = "width:250px" })
    </div>

    <div class="col-sm-2 text-right">
        <label class="control-label">Length:</label>
    </div>

    <div class="col-sm-1 form-group">
        @Html.TextBoxFor(m => m.BoatDetails.Length, new { @class = "form-control", @style = "width:70px", @type = "number" })
    </div>

    <div class="col-sm-1 text-right">
        <label class="control-label">Make:</label>
    </div>

    <div class="col-sm-2 form-group">
        
        @Html.DropDownListFor(m => m.BoatDetails.MakeId, new SelectList(Model.BoatMakeList,"key","value"),
        "", new
             {
                 @class = "form-control",
               @style = "width:150px"
             })
    </div>

    
</div>


<div class="row">

    <div class="col-sm-1 text-left">
        <label class="control-label">Type:</label>
    </div>

    <div class="col-sm-2 form-group">
        @Html.DropDownListFor(m => m.BoatDetails.TypeId, new SelectList(Model.BoatTypeList, "key", "value"),
       "", new
            {
                @class = "form-control",
              @style = "width:150px"
            })
    </div>

    <div class="col-sm-1 text-right">
        <label class="control-label">Pier:</label>
    </div>

    <div class="col-sm-1 form-group">
        @Html.DropDownListFor(m => m.BoatDetails.Pier, new SelectList(Model.PierList),
        "", new
             {
                 @class = "form-control",
            @style = "width:70px"
             })
    </div>

    <div class="col-sm-1 text-right">
        <label class="control-label">Berth:</label>
    </div>

    <div class="col-sm-1 form-group">
        @Html.TextBoxFor(m => m.BoatDetails.Berth, new { @class = "form-control", @style = "width:245px" })
    </div>

</div>

<div class="row">

    <div class="col-sm-2 text-left">
        <label class="control-label">Owner First Name:</label>
    </div>

    <div class="col-sm-2 form-group">
        @Html.TextBoxFor(m => m.BoatDetails.OwnerFirstName, new { @class = "form-control", @style = "width:150px" })
    </div>

    <div class="col-sm-2 text-right">
        <label class="control-label">Owner Last Name:</label>
    </div>

    <div class="col-sm-2 form-group">
        @Html.TextBoxFor(m => m.BoatDetails.OwnerLastName, new { @class = "form-control", @style = "width:160px" })
    </div>

  
</div>

<div class="row">


    <div class="col-sm-2 text-left">
        <label class="control-label">Owner Address:</label>
    </div>

    <div class="col-sm-8 form-group">
        @Html.TextBoxFor(m => m.BoatDetails.OwnerAddress, new { @class = "form-control", @style = "width:505px" })
    </div>

    
</div>

<div class="row">



    <div class="col-sm-2 text-left">
        <label class="control-label">Owner Telephone:</label>
    </div>

    <div class="col-sm-2 form-group">
        @Html.TextBoxFor(m => m.BoatDetails.OwnerTelephone, new { @class = "form-control", @style = "width:120px" })
    </div>

    <div class="col-sm-2 text-right">
        <label class="control-label">Owner Email:</label>
    </div>

    <div class="col-sm-2 form-group">
        @Html.TextBoxFor(m => m.BoatDetails.OwnerEmail, new { @class = "form-control", @style = "width:160px", @type="email" })
    </div>
</div>

<div class="row">
   
    <div class="col-xs-4" id="mandatory">
       *** All the fields are required ***
    </div>

</div>

<div class="row">
    <div class="col-sm-2 text-right">
        &nbsp;
    </div>

    <div class="col-xs-4">
        <button type="button" class="btn btn-xs btn-primary CRUDButton" id="btnSave">Add New</button>
        <button type="button" class="btn btn-xs btn-danger CRUDButton" id="btnReset">Cancel</button>
       <button type="button" class="btn btn-xs btn-warning CRUDButton" id="btnShowDeactivatePrompt"  >Deactivate</button>
    </div>

</div>



}

Code/KingsHillMarina/KingsHillMarina.WebApp/Views/BoatDetails/_BoatDetailsGrid.cshtml
@model KingsHillMarina.WebApp.Models.BoatDetailsVM


@{
    var boatDetailsList = Model.BoatDetailsList;
    var itemCount = boatDetailsList.Count;
    var itemNo = 0;
}

@if (boatDetailsList != null && boatDetailsList.Any())
{


    @*<div class="row">
        <div class="col-xs-4 float-left">
            <div class="btn btn-xs btn-primary">
                Boats Count
                <span class="badge"> @itemCount</span>
            </div>
        </div>
    </div>*@


    <div class="row">

        <div class="col-xs-12" style="overflow: auto;">
            <table id="tblBoatDetails" cellspacing="0" class="table table-striped table-condensed display grid-view" style="width:100%">
                <thead>
                    <tr>
                        <td class="itemNumber"> Item No.</td>
                        <td>Name</td>
                        <td>Length (m)</td>
                        <td>Make</td>
                        <td>Type</td>
                        <td>Pier</td>
                        <td>Berth</td>
                        <td>Date Berthed</td>
                        <td>Charge (£)</td>
                        <td>Owner First Name</td>
                        <td>Owner Last Name</td>
                        <td class="col-xs-4">Owner Address</td>
                        <td>Owner Telephone</td>
                        <td>Owner Email</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var boatDetails in boatDetailsList)
                    {
                        itemNo++;

                    <tr class='clickable-row' style="cursor:pointer;" data-id="@boatDetails.Id" title="Click the row to update boat details">
                        <td class="col-xs-1 itemNumber">@itemNo</td>

                        <td class="col-xs-4">
                            @boatDetails.Name
                        </td>
                        <td class="col-xs-1">
                            @boatDetails.Length
                        </td>
                        <td class="col-xs-3">
                            @boatDetails.Make
                        </td>
                        <td class="col-xs-2">
                            @boatDetails.Type
                        </td>
                        <td class="col-xs-1">
                            @boatDetails.Pier
                        </td>
                        <td class="col-xs-2">
                            @boatDetails.Berth
                        </td>
                        <td class="col-xs-2">
                            @boatDetails.DateBerthed.ToString("dd/MM/yyyy")
                        </td>
                        <td class="col-xs-2">
                            @if (boatDetails.Charge > 0)
                            {
                                @boatDetails.Charge
                            }
                        </td>
                        <td class="col-xs-2">
                            @boatDetails.OwnerFirstName
                        </td>
                        <td class="col-xs-2">
                            @boatDetails.OwnerLastName
                        </td>
                        <td class="col-xs-6">
                            @boatDetails.OwnerAddress
                        </td>
                        <td class="col-xs-2">
                            @boatDetails.OwnerTelephone
                        </td>
                        <td class="col-xs-2">
                            @boatDetails.OwnerEmail
                        </td>

                    </tr>
                    }

                </tbody>
            </table>
        </div>


      


    </div>


 }

<script type="text/javascript">

    $(function () {

        $('.clickable-row').on('click', function () {

            $('table tr').removeClass("selectedRow");
            $(this).addClass("selectedRow");
            var id = $(this).data('id');
            $('#btnShowDeactivatePrompt').show();
            $('#btnSave').text('Update');
            PopulateBoatDetails(id);

        });

    });

    function PopulateBoatDetails(id) {


        $.get('/BoatDetails/GetById', { id: id }).done(function (data) {

            $('#BoatDetails_Id').val(data.Id);
            $('#BoatDetails_Name').val(data.Name);
            $('#BoatDetails_Length').val(data.Length);
            $('#BoatDetails_MakeId').val(data.MakeId);
            $('#BoatDetails_TypeId').val(data.TypeId);
            $('#BoatDetails_Pier').val(data.Pier);
            $('#BoatDetails_Berth').val(data.Berth);
            $('#BoatDetails_OwnerFirstName').val(data.OwnerFirstName);
            $('#BoatDetails_OwnerLastName').val(data.OwnerLastName);
            $('#BoatDetails_OwnerAddress').val(data.OwnerAddress);
            $('#BoatDetails_OwnerTelephone').val(data.OwnerTelephone);
            $('#BoatDetails_OwnerEmail').val(data.OwnerEmail);

            window.scrollTo(0, 0)  // Scroll th window to top

        })
            .fail(function (xdata) {

                Msg.error('Error occured! <b>Status:</b> ' + xdata.status + ' <b>Error Message:</b> ' + xdata.statusText, 5 * 1000);
            })
            .always(function () {


            });
    }

</script>

<script src="~/Scripts/Custom/DataTable.js?v=@DateTime.Now.ToString("yyyyMMddHHmmss")"></script>