Code/KingsHillMarina/KingsHillMarina.WebApp/Controllers/LookupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KingsHillMarina.Domain.Abstractions;
using KingsHillMarina.Domain;
using KingsHillMarina.Repositories;
using KingsHillMarina.WebApp.Models;

namespace KingsHillMarina.WebApp.Controllers
{
    public class LookupsController : BaseController
    {
        private readonly ILookupsService _lookupsService;

        public LookupsController(ILookupsService lookupsService)
        {
            this._lookupsService = lookupsService ?? throw new ArgumentNullException(
                       $"LookupsController expects ctor injection: {nameof(ILookupsService)}");
        }

        private enum LookupsType
        {
            BoatMake,
            BoatType,
            Charge
        }

        // GET: Lookups
        public ActionResult Index(string type)
        {
            var vm = new LookupsVM();

            if (string.IsNullOrWhiteSpace(type))
            {
                type = "BoatMake";
            }

            switch (type)
            {
                case "BoatMake":
                    vm.BoatMakes = _lookupsService.GetBoatMakes()?.ToList();
                    vm.BoatMake = new BoatMake();
                    type = LookupsType.BoatMake.ToString();
                    break;

                case "BoatType":
                    vm.BoatTypes = _lookupsService.GetBoatTypes()?.ToList();
                    vm.BoatType = new BoatType();
                    type = LookupsType.BoatType.ToString();
                    break;

                case "Charge":
                    vm.Charge = _lookupsService.GetCharge() as Charge;
                    type = LookupsType.Charge.ToString();
                    break;

                default:
                    vm.BoatMakes = _lookupsService.GetBoatMakes()?.ToList();
                    vm.BoatMake = new BoatMake();
                    type = LookupsType.BoatMake.ToString();
                    break;
            }

            vm.Type = type;
            return View(vm); ;
        }

        public ActionResult GetBoatMakeById(int id)
        {
            var boatDetail = _lookupsService.GetBoatMakeById(id);
            return Json(boatDetail, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetBoatTypeById(int id)
        {
            var boatDetail = _lookupsService.GetBoatTypeById(id);
            return Json(boatDetail, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult SaveBoatMake(LookupsVM model)
        {

            var vm = new LookupsVM();
            var boatMake = model.BoatMake;
            string resultMsg = "Boat Make saved successfully";

            //Validate 
            if (string.IsNullOrWhiteSpace(boatMake.Name))
            {
                return Json(
                    new
                    {
                        success = false,
                        msg = "Please supply boat make and continue.... "
                    });
            }


            bool result = _lookupsService.SaveBoatMake(boatMake);

            if (!result)
            {
                resultMsg = "Boat Make saving failed!";
            }

            vm.BoatMakes = _lookupsService.GetBoatMakes()?.ToList();

            var partialView = RenderPartialViewToString(
                                   "_BoatMake",
                                   vm);

            JsonResult jsonResult = Json(new
            {
                success = result,
                msg = resultMsg,
                partialView = partialView
            }, JsonRequestBehavior.AllowGet);

            //The default is 102400 characters: http://msdn.microsoft.com/en-us/library/system.web.configuration.scriptingjsonserializationsection.maxjsonlength(v=vs.110).aspx
            jsonResult.MaxJsonLength = int.MaxValue;  //The value of this constant is 2,147,483,647

            return jsonResult;
        }

        [HttpPost]
        public ActionResult SaveBoatType(LookupsVM model)
        {
            var vm = new LookupsVM();
            var boatType = model.BoatType;
            string resultMsg = "Boat Type saved successfully";
           

            //Validate 
            if (string.IsNullOrWhiteSpace(boatType.Name))
            {
                return Json(
                    new
                    {
                        success = false,
                        msg = "Please supply boat type and continue.... "
                    });
            }

            bool result = _lookupsService.SaveBoatType(boatType);

            if (!result)
            {
                resultMsg = "Boat Type saving failed!";
            }

            vm.BoatTypes = _lookupsService.GetBoatTypes()?.ToList();

            var partialView = RenderPartialViewToString(
                                   "_BoatType",
                                   vm);

            JsonResult jsonResult = Json(new
            {
                success = result,
                msg = resultMsg,
                partialView = partialView
            }, JsonRequestBehavior.AllowGet);

            //The default is 102400 characters: http://msdn.microsoft.com/en-us/library/system.web.configuration.scriptingjsonserializationsection.maxjsonlength(v=vs.110).aspx
            jsonResult.MaxJsonLength = int.MaxValue;  //The value of this constant is 2,147,483,647

            return jsonResult;
        }

        [HttpPost]
        public ActionResult SaveCharge(LookupsVM model)
        {
            var vm = new LookupsVM();
            var charge = model.Charge;
            string resultMsg = "Charge saved successfully";


            //Validate 
            if (charge.Amount <= 0)
            {
                return Json(
                    new
                    {
                        success = false,
                        msg = "Please supply amount and continue.... "
                    });
            }

            if (charge.VAT <= 0)
            {
                return Json(
                    new
                    {
                        success = false,
                        msg = "Please supply VAT and continue.... "
                    });
            }

            bool result = _lookupsService.SaveCharge(charge); ;

            if (!result)
            {
                resultMsg = "Charge saving failed!";
            }

            vm.Charge = _lookupsService.GetCharge() as Charge;

            var partialView = RenderPartialViewToString(
                                   "_Charge",
                                   vm);

            JsonResult jsonResult = Json(new
            {
                success = result,
                msg = resultMsg,
                partialView = partialView
            }, JsonRequestBehavior.AllowGet);

            //The default is 102400 characters: http://msdn.microsoft.com/en-us/library/system.web.configuration.scriptingjsonserializationsection.maxjsonlength(v=vs.110).aspx
            jsonResult.MaxJsonLength = int.MaxValue;  //The value of this constant is 2,147,483,647

            return jsonResult;
        }

    }

}

Code/KingsHillMarina/KingsHillMarina.WebApp/Views/Lookups/Index.cshtml
@model KingsHillMarina.WebApp.Models.LookupsVM


@{
    ViewBag.Title = "Lookups management";
    var type = Model.Type;
}

<div class="bs-callout bs-callout-primary">

    <p class="well lead bs-callout bs-callout-primary" style="font-weight:bolder">Lookups Management</p>

    <ul class="nav nav-tabs" style="margin-bottom:10px;">
        <li id="BoatMake" class="cursor no-wrap" onclick="showRegion('BoatMake')">
            <a href="" data-toggle="tab">Boat Make</a>
        </li>
        <li id="BoatType" class="cursor no-wrap" onclick="showRegion('BoatType')">
            <a href="" data-toggle="tab">Boat Type</a>
        </li>
        <li id="Charge" class="cursor no-wrap" onclick="showRegion('Charge')">
            <a href="" data-toggle="tab">Charge</a>
        </li>

    </ul>

    @if (type == "BoatMake")
    {
        <div id="divBoatMake">
            @{ Html.RenderPartial("_BoatMake", Model); }
        </div>
       
    }
    else if (type == "BoatType")

    {
        <div id="divBoatType">
            @{ Html.RenderPartial("_BoatType", Model); }
        </div>
       
    }
    else if (type == "Charge")
    {
        <div id="divCharge">
            @{ Html.RenderPartial("_Charge", Model); }
        </div>
       
    }
  
</div>

<script type="text/javascript" src="~/Scripts/Custom/Tabs.js?v=@DateTime.Now.ToString("yyyyMMddHHmmss")"></script>
<script type="text/javascript" src="~/Scripts/Custom/Lookups.js?v=@DateTime.Now.ToString("yyyyMMddHHmmss")"></script>

Code/KingsHillMarina/KingsHillMarina.WebApp/Views/Lookups/_BoatMake.cshtml
@model KingsHillMarina.WebApp.Models.LookupsVM


@{
    var boatMakes = Model.BoatMakes;
    var itemNo = 0;

}

<h4>Boat Makes</h4>


@using (Html.BeginForm("SaveMake", "Lookups", FormMethod.Post, new { @class = "form-horizontal form-group-sm", @style = "margin-top: 20px;", @id = "frmBoatMake" }))
{
    @Html.HiddenFor(m => m.BoatMake.Id);

    <div class="row">
        <div class="col-sm-1 text-left">
            <label class="control-label">Name:</label>
        </div>

        <div class="col-sm-2 form-group">
            @Html.TextBoxFor(m => m.BoatMake.Name, new { @class = "form-control", @style = "width:250px" })
        </div>
    </div>

    <div class="row">
        <div class="col-sm-1 text-right">
            &nbsp;
        </div>

        <div class="col-xs-4">
            <button type="button" class="btn btn-xs btn-primary CRUDButton" id="btnSaveBoatMake">Add New</button>
            <button type="button" class="btn btn-xs btn-danger CRUDButton" id="btnResetBoatMake">Cancel</button>
        </div>

    </div>

}

<div class="row">
    <div class="col-xs-12">
        &nbsp;
    </div>
</div>



@if (boatMakes != null && boatMakes.Any())
{
    <div class="row">

        <div class="col-xs-12" style="overflow: auto;">
            <table id="tblBoatMakes" cellspacing="0" class="table table-striped table-condensed display grid-view" style="width:100%">
                <thead>
                    <tr>
                        <td class="itemNumber"> Item No.</td>
                        <td>Name</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var boatMake in boatMakes)
                    {
                        itemNo++;

                        <tr class="clickable-boatmake-row" style="cursor:pointer;" data-id="@boatMake.Id" title="Click the row to update boat make">
                            <td class="col-xs-1 itemNumber">@itemNo</td>

                            <td class="col-xs-4">
                                @boatMake.Name
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>

    </div>

}


<script src="~/Scripts/Custom/DataTable.js?v=@DateTime.Now.ToString("yyyyMMddHHmmss")"></script>

<script type="text/javascript">

    $(function () {


        $('.clickable-boatmake-row').on('click', function () {

            $('table tr').removeClass("selectedRow");
            $(this).addClass("selectedRow");
            var id = $(this).data('id');
            $('#btnSaveBoatMake').text('Update');
            GetBoatMakeById(id);

        });

    });

    function GetBoatMakeById(id) {

        $.get('/Lookups/GetBoatMakeById', { id: id }).done(function (data) {

            $('#BoatMake_Id').val(data.Id);
            $('#BoatMake_Name').val(data.Name);
            window.scrollTo(0, 0)  // Scroll th window to top

        })
            .fail(function (xdata) {

                Msg.error('Error occured! <b>Status:</b> ' + xdata.status + ' <b>Error Message:</b> ' + xdata.statusText, 5 * 1000);
            })
            .always(function () {


            });

    }
</script>

Code/KingsHillMarina/KingsHillMarina.WebApp/Views/Lookups/_BoatType.cshtml
@model KingsHillMarina.WebApp.Models.LookupsVM


@{
    var boatTypes = Model.BoatTypes;
    var itemNo = 0;

}

<h4>Boat Types</h4>

@using (Html.BeginForm("SaveType", "Lookups", FormMethod.Post, new { @class = "form-horizontal form-group-sm", @style = "margin-top: 20px;", @id = "frmBoatType" }))
{
    @Html.HiddenFor(m => m.BoatType.Id);

    <div class="row">
        <div class="col-sm-1 text-left">
            <label class="control-label">Name:</label>
        </div>

        <div class="col-sm-2 form-group">
            @Html.TextBoxFor(m => m.BoatType.Name, new { @class = "form-control", @style = "width:250px" })
        </div>
    </div>

    <div class="row">
        <div class="col-sm-1 text-right">
            &nbsp;
        </div>

        <div class="col-xs-4">
            <button type="button" class="btn btn-xs btn-primary CRUDButton" id="btnSaveBoatType">Add New</button>
            <button type="button" class="btn btn-xs btn-danger CRUDButton" id="btnResetBoatType">Cancel</button>
        </div>

    </div>

}


<div class="row">
    <div class="col-xs-12">
        &nbsp;
    </div>
</div>


@if (boatTypes != null && boatTypes.Any())
{
    <div class="row">

        <div class="col-xs-12" style="overflow: auto;">
            <table id="tblBoatTypes" cellspacing="0" class="table table-striped table-condensed display grid-view" style="width:100%">
                <thead>
                    <tr>
                        <td class="itemNumber"> Item No.</td>
                        <td>Name</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var boatType in boatTypes)
                    {
                        itemNo++;
                        <tr class="clickable-boattype-row" style="cursor:pointer;" data-id="@boatType.Id" title="Click the row to update boat type">
                            <td class="col-xs-1 itemNumber">@itemNo</td>

                            <td class="col-xs-4">
                                @boatType.Name
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>

    </div>

}

<script src="~/Scripts/Custom/DataTable.js?v=@DateTime.Now.ToString("yyyyMMddHHmmss")"></script>


<script type="text/javascript">

    $(function () {

        $('.clickable-boattype-row').on('click', function () {

            $('table tr').removeClass("selectedRow");
            $(this).addClass("selectedRow");
            var id = $(this).data('id');
            $('#btnSaveBoatType').text('Update');
            GetBoatTypeById(id);

        });

    });



    function GetBoatTypeById(id) {

        $.get('/Lookups/GetBoatTypeById', { id: id }).done(function (data) {

            $('#BoatType_Id').val(data.Id);
            $('#BoatType_Name').val(data.Name);
            window.scrollTo(0, 0)  // Scroll th window to top

        })
            .fail(function (xdata) {

                Msg.error('Error occured! <b>Status:</b> ' + xdata.status + ' <b>Error Message:</b> ' + xdata.statusText, 5 * 1000);
            })
            .always(function () {


            });

    }



</script>

Code/KingsHillMarina/KingsHillMarina.WebApp/Views/Lookups/_Charge.cshtml
@model KingsHillMarina.WebApp.Models.LookupsVM

<h4>Charge</h4>

@using (Html.BeginForm("SaveChar", "Lookups", FormMethod.Post, new { @class = "form-horizontal form-group-sm", @style = "margin-top: 20px;", @id = "frmCharge" }))
{
    @Html.HiddenFor(m => m.Charge.Id);

<div class="row">
    <div class="col-sm-2 text-left">
        <label class="control-label">Amount (£}:</label>
    </div>

    <div class="col-sm-1 form-group">
        @Html.TextBoxFor(m => m.Charge.Amount, new { @class = "form-control", @style = "width:100px" , @type="number"})
    </div>

    <div class="col-sm-2 text-right">
        <label class="control-label">VAT (%):</label>
    </div>

    <div class="col-sm-1 form-group">
        @Html.TextBoxFor(m => m.Charge.VAT, new { @class = "form-control", @style = "width:100px",  @type = "number" })
    </div>
</div>

    <div class="row">
        <div class="col-sm-2 text-right">
            &nbsp;
        </div>

        <div class="col-xs-4">
            <button type="button" class="btn btn-xs btn-primary CRUDButton" id="btnSaveCharge">Save</button>
            <button type="button" class="btn btn-xs btn-danger CRUDButton" id="btnResetCharge">Cancel</button>
        </div>

    </div>

}